---
  - hosts: all
    become: true

    vars:
      motd:
         -  Ansible Managed Node by nowellgabriel

    vars_prompt:
        - name: username
          prompt: Input Username
          private: false

        - name: uid
          prompt: Input UID
          private: false

    tasks:

    - name: Banner MOTD
      ansible.builtin.debug:
        msg:
          - "{{ motd }}"

    - name: install python3 and pip3 for UBUNTU
      apt:
        name:
          - python3
          - python3-pip
        state: latest
        update_cache: yes
      when: ansible_distribution == "ubuntu"

    - name: install python3 and pip3 for CentOS
      package:
        name:
          - python3
          - python3-pip
        state: latest
        update_cache: yes
      when: ansible_distribution == "centos"

    - name: Install open-jdk for Ubuntu
      apt:
        name:
          - openjdk-17-jdk
        state: latest
        update_cache: yes
      when: ansible_distribution == "ubuntu"

    - name: Install open-jdk for CentOS
      yum:
        name:
          - java-11-openjdk
        state: latest
        update_cache: yes
      when: ansible_distribution == "centos"

    - name: Create a User
      ansible.builtin.user:
        name: "{{ username }}"
        comment: New User
        uid: "{{ uid }}"
        createhome: yes
        home: /home/"{{ username }}"
        shell: /bin/bash
